// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB_iopFlDkufJAOc7cr8TUfPcdjnlP_oM',
    appId: '1:916683131497:web:a7fe27944e4739859e70f8',
    messagingSenderId: '916683131497',
    projectId: 'solverside-6dd9e',
    authDomain: 'solverside-6dd9e.firebaseapp.com',
    storageBucket: 'solverside-6dd9e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1ubL-sWVnerWITtN9yDSxxGAJukiEILk',
    appId: '1:916683131497:android:e314e9841f26a7d99e70f8',
    messagingSenderId: '916683131497',
    projectId: 'solverside-6dd9e',
    storageBucket: 'solverside-6dd9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGABxilI68-lcr3BW48KD4BeefDUID3ek',
    appId: '1:916683131497:ios:f4a43d1304f4cda79e70f8',
    messagingSenderId: '916683131497',
    projectId: 'solverside-6dd9e',
    storageBucket: 'solverside-6dd9e.appspot.com',
    iosBundleId: 'com.example.assignmentSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGABxilI68-lcr3BW48KD4BeefDUID3ek',
    appId: '1:916683131497:ios:f4a43d1304f4cda79e70f8',
    messagingSenderId: '916683131497',
    projectId: 'solverside-6dd9e',
    storageBucket: 'solverside-6dd9e.appspot.com',
    iosBundleId: 'com.example.assignmentSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCB_iopFlDkufJAOc7cr8TUfPcdjnlP_oM',
    appId: '1:916683131497:web:72fd1d6c3a7e9ba39e70f8',
    messagingSenderId: '916683131497',
    projectId: 'solverside-6dd9e',
    authDomain: 'solverside-6dd9e.firebaseapp.com',
    storageBucket: 'solverside-6dd9e.appspot.com',
  );
}
